---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: le-ingress
  annotations:
    # cert-manager.io/issuer: le-letsencrypt
    # kubernetes.io/ingress.class: nginx
    cloud.google.com/neg: "{\"ingress\": true}"
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: le-public-ipv4
spec:
  defaultBackend:
    service:
      name: le-redirects
      port:
        name: "http"
  #  tls:
  #  - secretName: le-web-ssl
  #    hosts:
  #      - "longforman.cz"
  #      - "polocas-napadu.cz"
  #      - "polocasnapadu.cz"
  #      - "*.longforman.cz"
  #      - "*.polocas-napadu.cz"
  #      - "*.polocasnapadu.cz"
  #      - "*.staging.polocas-napadu.cz"
  rules:
    - host: "pm.polocas-napadu.cz"
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: le-redmine
                port:
                  name: http
