---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: sg-letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: pavel.zak@polocas-napadu.cz
    privateKeySecretRef:
      name: sg-letsencrypt
    solvers:
      - http01:
          ingress:
            name: le-ingress
