---
name: Deployment
on:
  workflow_run:
    workflows: ["Integration"]
    types:
      - completed
    branches:
      - master
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs:
      - build
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: abatilo/actions-poetry@v2
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v3
      - name: Download docker image
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: polocas-api-docker
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/polocas-api.tar
          docker image ls -a
      - name: Deploy with terraform
        working-directory: polocas/terraform
        run: terraform apply