---
name: Integration
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-22.04
    env:
      wd: "./polocas/api"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: |
          sudo apt-get install gettext
          poetry install --no-interaction --no-root
        working-directory: ${{env.wd}}
      - name: Test
        run: poetry run pytest --cov-report=xml --cov-config=.coveragerc --cov="."
        working-directory: ${{env.wd}}
      - name: Static code analysis
        run: poetry run prospector -s high
        working-directory: ${{env.wd}}
      - name: Compile messages
        run: poetry run ./manage.py compilemessages
        working-directory: ${{env.wd}}
      - name: Lock requirements
        run: poetry export -f requirements.txt --output requirements.txt
        working-directory: ${{env.wd}}
      - name: Compile artifacts
        run: poetry build
        working-directory: ${{env.wd}}
      - uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{env.wd}}
          tags: polocas-api:latest
          outputs: type=docker,dest=/tmp/polocas-api.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: polocas-api-docker
          path: /tmp/polocas-api.tar

  build-redmine:
    name: Build Redmine
    runs-on: ubuntu-22.04
    env:
      wd: "./polocas/redmine"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{env.wd}}
          tags: polocas-redmine:latest
          outputs: type=docker,dest=/tmp/polocas-redmine.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: polocas-redmine-docker
          path: /tmp/polocas-redmine.tar

  build-redirects:
    name: Build Redirects
    runs-on: ubuntu-22.04
    env:
      wd: "./polocas/redirects"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build @polocas/redirects
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{env.wd}}
          tags: polocas-redmine:latest
          outputs: type=docker,dest=/tmp/polocas-redirects.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: polocas-redmine-docker
          path: /tmp/polocas-redirects.tar
